# Spring boot application
spring:
  application:
    name: dubbo-provider-demo
  datasource:
    name: so
    url: jdbc:mysql://localhost:3306/so?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 9090

#mappers
mapper :
  mappers :
  not-empty : false
  identity : MYSQL

pagehelper :
  helperDialect : mysql
  reasonable : true
  supportMethodsArguments : true
  params : count=countSql

management:
  port: 9091

mybatis :
  mapper-locations : classpath:com/wenyao/mapper/xml/*.xml
  type-aliases-package : com.wenyao.entity
  configuration :
    mapUnderscoreToCamelCase : true
    map-underscore-to-camel-case : true

# Service version
demo:
  service:
    version: 1.0.0

# Base packages to scan Dubbo Components (e.g @Service , @Reference)
dubbo:
  scan:
    basePackages: com.wenyao.service.impl
  application:
    id: dubbo-provider-demo
    name: dubbo-provider-demo
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    id: my-registry
    address: N/A