# Spring boot application
spring:
  application:
    name: dubbo-provider-demo
server:
  port: 9090
management:
  port: 9091

# Service version
demo:
  service:
    version: 1.0.0

# Base packages to scan Dubbo Components (e.g @Service , @Reference)
dubbo:
  scan:
    basePackages: com.wenyao.service.impl
  application:
    id: dubbo-provider-demo
    name: dubbo-provider-demo
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    id: my-registry
    address: N/A